# Generated by Django 3.2.9 on 2021-12-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211203_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='flag.png', null=True, upload_to=''),
        ),
    ]
